version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.1

jobs:
  run_tests_job:
    docker:
      - image: circleci/clojure:lein-2.9.5
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: 'lein test'
      - run: 'lein cloverage -o cov --coveralls'
      - coveralls/upload

workflows:
  run_tests:
    jobs:
      - run_tests_job

